---
title: Creating Dashboards with Shiny
runtime: shiny
output: html_document
---

# 1. Housing prices dashboard

# 1.1 Code for displaying dashboard in R Markdown

```{r echo=TRUE, results='hide'}
library(shiny)
library(DT)
library(dplyr)
library(readr)

# Load data
house <- read.csv('houseprices.csv')

# Get lists of all neighbourhoods and which to exclude by default, for plotting
house$Neighborhood = as.factor(house$Neighborhood) # for levels to be pulled, it needs to be formatted as factor
all_neighbourhoods <- levels(pull(house, 'Neighborhood'))
exclude_neighbourhoods <- setdiff(levels(house$Neighborhood), c("Blmngtn", "StoneBr", "Mitchel", "OldTown", "NoRidge"))

# Define UI for application
fluidPage(
  # Application title
  titlePanel("Iowa Housing: Sale Price"),
  
  # Sidebar with various Exploratory Data Analysis choices
  sidebarLayout(
    sidebarPanel(
       # Select variable for x-axis
       selectInput(inputId = "x",
                   label = "X-axis:",
                   choices = c("GrLivArea", "TotalSF", "TotalBsmtSF", "HouseAge"),
                   selected = "GrLivArea"),
       
       # Select variable for colour
       selectInput(inputId = "z",
                   label = "Colour:",
                   choices = c("Neighborhood", "CentralAir", "MSSubClass", "SaleType", "SaleCondition", "Foundation"),
                   selected = "Neighborhood"),
       
       # Select the number of smoothing splines vs. SalePrice
       sliderInput(inputId = "splines",
                   label = "Smoothing splines:", 
                   min = 1, max = 19, step = 2,
                   value = 5),
       
       # Select which neighbourhoods to exclude from the plot, as it can get cluttered quickly
       selectInput(inputId = "neighbourhoods",
                   label = "Exclude neighbourhoods:",
                   choices = all_neighbourhoods,
                   selected = exclude_neighbourhoods,
                   multiple = TRUE,
                   selectize = TRUE),
       
       # Place the boxplot on the lower left side
       plotOutput(outputId = "boxPlot")
    ),
    
    # Show scatter plot and table of selected data on the right side (main area)
    mainPanel(
       plotOutput(outputId = "scatterPlot", brush = "plot_brush"),
       htmlOutput(outputId = "instructions"),
       dataTableOutput(outputId = "houseTable"),
       br()
    )
  )
)

# Define server logic required to draw the plots
function(input, output) {
output$scatterPlot <- renderPlot({
  ggplot(data = house %>% filter(!(Neighborhood %in% input$neighbourhoods)),
          aes_string(x = input$x, y = "SalePrice")) +
    geom_point(aes_string(col = input$z)) +
    geom_smooth(method = "lm", formula = y ~ splines::bs(x, input$splines), se = F) +
    labs(
      y = "Sale Price ($)"
    )
})
  
output$boxPlot <- renderPlot({
  ggplot(data = house %>% filter(!(Neighborhood %in% input$neighbourhoods))) +
    geom_boxplot(aes_string(x = input$z, y = "SalePrice", fill = input$z)) +
    theme(legend.position="none",
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank()) +
    labs(
      x = ""
    )
})
  
output$instructions <- renderUI({
    HTML("Click and drag selection of observations in scatter plot to inspect closer.<br>")
})
  
  # Create data table
output$houseTable <- DT::renderDataTable({
    brushedPoints(house, brush = input$plot_brush) %>% 
      filter(!(Neighborhood %in% input$neighbourhoods)) %>%
      select(SalePrice, Neighborhood, TotalSF, HouseAge, SaleCondition, GarageCars, GarageAge)
})
}
```

## 1.2 The dashboard

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(shiny)
library(DT)
library(readr)
library(dplyr)
library(ggplot2)

# Load data
house <- read.csv('houseprices.csv')

# Get lists of all neighbourhoods and which to exclude by default, for plotting
house$Neighborhood = as.factor(house$Neighborhood) # for levels to be pulled, it needs to be formatted as factor
all_neighbourhoods <- levels(pull(house, 'Neighborhood'))
exclude_neighbourhoods <- setdiff(levels(house$Neighborhood), c("Blmngtn", "StoneBr", "Mitchel", "OldTown", "NoRidge"))

# Define UI for application
fluidPage(
  # Application title
  titlePanel("Iowa Housing: Sale Price"),
  
  # Sidebar with various Exploratory Data Analysis choices
  sidebarLayout(
    sidebarPanel(
       # Select variable for x-axis
       selectInput(inputId = "x",
                   label = "X-axis:",
                   choices = c("GrLivArea", "TotalSF", "TotalBsmtSF", "HouseAge"),
                   selected = "GrLivArea"),
       
       # Select variable for colour
       selectInput(inputId = "z",
                   label = "Colour:",
                   choices = c("Neighborhood", "CentralAir", "MSSubClass", "SaleType", "SaleCondition", "Foundation"),
                   selected = "Neighborhood"),
       
       # Select the number of smoothing splines vs. SalePrice
       sliderInput(inputId = "splines",
                   label = "Smoothing splines:", 
                   min = 1, max = 19, step = 2,
                   value = 5),
       
       # Select which neighbourhoods to exclude from the plot, as it can get cluttered quickly
       selectInput(inputId = "neighbourhoods",
                   label = "Exclude neighbourhoods:",
                   choices = all_neighbourhoods,
                   selected = exclude_neighbourhoods,
                   multiple = TRUE,
                   selectize = TRUE),
       
       # Place the boxplot on the lower left side
       plotOutput(outputId = "boxPlot")
    ),
    
    # Show scatter plot and table of selected data on the right side (main area)
    mainPanel(
       plotOutput(outputId = "scatterPlot", brush = "plot_brush"),
       htmlOutput(outputId = "instructions"),
       dataTableOutput(outputId = "houseTable"),
       br()
    )
  )
)

# Define server logic required to draw the plots
output$scatterPlot <- renderPlot({
  ggplot(data = house %>% filter(!(Neighborhood %in% input$neighbourhoods)),
          aes_string(x = input$x, y = "SalePrice")) +
    geom_point(aes_string(col = input$z)) +
    geom_smooth(method = "lm", formula = y ~ splines::bs(x, input$splines), se = F) +
    labs(
      y = "Sale Price ($)"
    )
})
  
output$boxPlot <- renderPlot({
  ggplot(data = house %>% filter(!(Neighborhood %in% input$neighbourhoods))) +
    geom_boxplot(aes_string(x = input$z, y = "SalePrice", fill = input$z)) +
    theme(legend.position="none",
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank()) +
    labs(
      x = ""
    )
})
  
output$instructions <- renderUI({
    HTML("Click and drag selection of observations in scatter plot to inspect closer.<br>")
})
  
# Create data table
output$houseTable <- DT::renderDataTable({
    brushedPoints(house, brush = input$plot_brush) %>% 
      filter(!(Neighborhood %in% input$neighbourhoods)) %>%
      select(SalePrice, Neighborhood, TotalSF, HouseAge, SaleCondition, GarageCars, GarageAge)
})

```

# 2. Threshold dashboard

## 2.1 Code for displaying dashboard in R Markdown 

```{r echo=TRUE, results='hide'}
library(shiny)
library(ggplot2)
load(file = "logfit.Rdata")

fluidPage(
  
  # Application title
  titlePanel("Threshold Analysis"),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(
    sidebarPanel(
      sliderInput("threshold",
                  "Threshold:",
                  min = 0.00,
                  max = 0.50,
                  value = 0.25),
      selectInput("models",
                  "Model",
                  choices = c("log", "lda", "qda"))
    ),
    # Show a plot of the generated distribution
    mainPanel(
      plotOutput("logfit", width = "100%", height = "500px"),
      plotOutput("threshold", width = "100%", height = "500px")
      #, width = 12
      )
  )
)

output$logfit <- renderPlot({
  plot.list[[input$models]] + geom_vline(xintercept=input$threshold, linetype = "dashed", color = "black")
  })
  
output$threshold <- renderPlot({
  confusion.matrix(table(ifelse(as.numeric(threshold.list[[input$models]] > input$threshold), 1, 0), test.data$y),
                   tit = paste0(input$models, " classification probability threshold ", input$threshold * 100, "%"))
  })
```

## 2.2 The dashboard

```{r echo=FALSE}
load(file = "logfit.Rdata")

fluidPage(
  
  # Application title
  titlePanel("Threshold Analysis"),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(
    sidebarPanel(
      sliderInput("threshold",
                  "Threshold:",
                  min = 0.00,
                  max = 0.50,
                  value = 0.25),
      selectInput("models",
                  "Model",
                  choices = c("log", "lda", "qda"))
    ),
    # Show a plot of the generated distribution
    mainPanel(
      plotOutput("logfit", width = "100%", height = "500px"),
      plotOutput("threshold", width = "100%", height = "500px"),
      width = 12)
  )
)

 output$logfit<- renderPlot({
    plot.list[[input$models]] + geom_vline(xintercept=input$threshold, linetype = "dashed", color = "black")
  })
  
  output$threshold <- renderPlot({
    confusion.matrix(table(ifelse(as.numeric(threshold.list[[input$models]] > input$threshold), 1, 0), test.data$y),
                     tit = paste0(input$models, " classification probability threshold ", input$threshold * 100, "%"))
    
  })
```